# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.27.0"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "58dd6f0aeb2b3bd22464be8963262f236f0c6e9c773143e95038fcdd4f73913a"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "9cac24d6cef83f629357a3a1c49cb59977a00d7b09a33192162a542ccf2ec96c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "41d53a7fe8431705b9498cb6da4c21e2d239f780f4992e78a534dd54f282ea81"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "b033967fb3125798b6555c6693b793a5df66ed4bb18bdda2527a4b8bf67da264"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
