# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.26.1"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "8318271ed84255a2fbf2bca5a78e952ca19992bd1d7ff17af738a4d5397960ed"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "c04b435abf14e3e3c5a800407150523a4412679fe4f18cb87c7c77f74fd79a1f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "649b65e06553680cc60b35a4977cdf9da862255e8b02d15d2bbfa7e605f2cbb2"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "958ad9d0d86592787e9b596f1bc7535677b61598f247b4beab2334946fdfe26a"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
