# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.19.0"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "85c7e0bee970d2b1d4697e70dba6daddbd523f3566604b46276043ae8fc3e99f"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "573e571144e8bee805755f4f52c033c502dab7182e48b8d7f1aedc961399f6e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "01ab01891208aadacb207e8f00afa2ab937eda1fef705acf51804caea9af459d"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "31095ec977ff526b4ea9843b066e101af1dcfbcbd2ae1380977bb6ff70e17d1c"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
